### PR TITLE
Feature/add instructions for new components

### PR DESCRIPTION
**Pull request by gtvj**
I've updated the README.md to:

1. Describe the purpose of this repository
2. Link to the development guide
3. Include a section describing steps to create a new component

### CODE REVIEW

**Comment by gtvj** [comment]
@AshTNA @JamesWChan @piriyapordes @ARBaynes - could someone have a look at this PR for me and ping me a message on Slack when it's been merged? It's just some changes to the README.md but I'd like to bring these changes into my next PR.

**Comment by ARBaynes** [comment]
@gtvj These changes all look good! I'm happy to merge this, although it seems that whatever SASS version we're using is causing the Travis build to throw a tantrum - should I bring this up as a separate issue?

**Comment by gtvj** [comment]
Thanks @ARBaynes - I suspect the issue relates to this: https://github.com/nationalarchives/tna-components/pull/20

Does this match what you’re seeing?

**Comment by ARBaynes** [comment]
Aaah, it does look like it relates to issue #20 @gtvj ! I'll merge now 😄

**Pull request merged**
